#!/usr/bin/env -S deno --ext=ts --allow-run --allow-read --allow-env

import { Command } from "https://deno.land/x/cliffy@v1.0.0-rc.4/command/mod.ts";
import { cliCommand as buildCommand } from "./scripts/cli-build.ts";
import { cliCommand as qemuCommand } from "./scripts/cli-qemu.ts";
import { logLevelEnum } from "./scripts/cli-types.ts";
import { parse } from "jsr:@std/yaml";
import { initPlatform } from "./scripts/platform.ts";

const command = new Command()
    .name("byteos")
    .version("0.1.0")
    .description("Building tools for the byteos.")
    .globalType("log-level", logLevelEnum)
    .globalOption("-l, --log-level <level:log-level>", "Set Log Level", {
        default: "info",
    })
    .globalOption("-p, --platform <string>", "Set the platform", {
        required: true,
    })
    .globalAction(({ platform }) => initPlatform(platform))
    // Sub Command build
    .command("build", buildCommand)
    .command("qemu", qemuCommand);

// parse yaml file
const data = parse(
    new TextDecoder("utf-8").decode(await Deno.readFile("byteos.yaml")),
);
console.log(data);

try {
    // Parse the command.
    await command.parse(Deno.args);
} catch (e) {
    console.error("Error", e);
}
