[workspace]
members = [
    # arch
    "arch",

    # crates

    # modules
    "modules/logging",
    "modules/panic_handler",
    "modules/kalloc",
    "modules/devices",
    "modules/frame_allocator",
    "modules/sync",
    "modules/hal",
    "modules/kheader",

    # kernel
    "kernel"
]
