[workspace]
resolver = "2"
members = [
    # arch
    "arch",

    # crates
    # "crates/backtrace",
    "crates/allocator",
    "crates/timestamp",
    "crates/vfscore",
    "crates/cv1811-sd",
    "crates/memory_addr",
    "crates/crate_interface",
    "crates/arm_pl011",
    "crates/arm_gic",
    "crates/percpu",
    "crates/percpu_macros",

    # modules
    "modules/logging",
    "modules/devices",
    "modules/frame_allocator",
    "modules/sync",
    "modules/hal",
    "modules/kheader",
    "modules/fs",
    "modules/devfs",
    "modules/ramfs",
    "modules/procfs",
    "modules/executor",
    "modules/signal",

    #drivers
    "drivers/*",

    # kernel
    "kernel"
]

[profile.release]
debug = true
