[workspace]
resolver = "2"
members = [
    # arch
    # "arch",

    # crates
    # "crates/backtrace",
    "crates/*",

    # modules
    "modules/*",

    #drivers
    "drivers/*",

    # kernel
    "kernel"
]

[profile.release]
debug = true
