[workspace]
resolver = "2"
members = [
    # arch
    "arch",

    # crates
    # "crates/backtrace",
    "crates/allocator",
    "crates/timestamp",
    "crates/vfscore",
    "crates/cv1811-sd",
    "crates/page_table",
    "crates/page_table_entry",
    "crates/memory_addr",
    "crates/crate_interface",

    # modules
    "modules/logging",
    "modules/devices",
    "modules/frame_allocator",
    "modules/sync",
    "modules/hal",
    "modules/kheader",
    "modules/fs",
    "modules/devfs",
    "modules/ramfs",
    "modules/procfs",
    "modules/executor",
    "modules/signal",

    #drivers
    "drivers/kgoldfish-rtc",
    "drivers/knvme",
    "drivers/kvirtio",
    "drivers/kcvitek-sd",
    "drivers/k210-sdcard",
    "drivers/general-plic",
    "drivers/ns16550a",

    # kernel
    "kernel"
]

[profile.release]
debug = true
