[workspace]
members = [
    # arch
    "arch",

    # crates
    "crates/console",

    # modules
    "modules/logging",
    "modules/panic_handler",
    "modules/kalloc",

    # kernel
    "kernel"
]
