[workspace]
members = [
    # arch
    "arch",

    # crates
    "crates/backtrace",
    "crates/timestamp",
    "crates/vfscore",
    
    # modules
    "modules/logging",
    "modules/panic_handler",
    "modules/kalloc",
    "modules/cv1811-sd",
    "modules/devices",
    "modules/frame_allocator",
    "modules/sync",
    "modules/hal",
    "modules/kheader",
    "modules/fs",
    "modules/devfs",
    "modules/ramfs",
    "modules/procfs",
    "modules/executor",
    "modules/signal",
    "modules/kmacros",
    "modules/kmacros/impl",

    # kernel
    "kernel"
]
