[toolchain]
profile = "minimal"
channel = "nightly-2023-03-29"
# channel = "nightly-2023-08-01"
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
targets = ["riscv64imac-unknown-none-elf"]