[base]
arch = "riscv64"
platform = "riscv64-qemu-virt"
family = "riscv64-qemu-virt"

kernel-paddr = "0x80200000"
kernel-vaddr = "0xffff_ffc0_8020_0000"

phys-virt-offset = "0xffff_ffc0_0000_0000"

[config]
allocator = "run"

[features]
