[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
board-k210 = []
board-cv1811h = []
net = []
nvme = []

[dependencies]
frame_allocator = { path = "../modules/frame_allocator" }
logging = { path = "../modules/logging" }
kalloc = { path = "../modules/kalloc" }
log = "0.4"
devices = { path = "../modules/devices" }
hal = { path = "../modules/hal" }
arch = { path = "../arch" }
fs = { path = "../modules/fs" }
executor = { path = "../modules/executor" }
xmas-elf = "0.9.0"
sync = { path = "../modules/sync" }
bitflags = "2.0.2"
signal = { path = "../modules/signal" }
bit_field = "0.10.1"
# lose-net-stack = { git = "https://github.com/yfblock/lose-net-stack", rev = "b06d136", features = ["log"]}
lose-net-stack = { path = "../../lose-net-stack", features = ["log"]}
vfscore = { path = "../crates/vfscore" }
async-recursion = "1.0.4"
futures-lite = { version = "1.13.0", default-features = false, features=["alloc"] }
kheader = { path = "../modules/kheader" }
backtrace = { path = "../crates/backtrace" }
hashbrown = "0.14"

num-traits = { version = "0.2", default-features = false}
num-derive = "0.4"

# drivers
knvme = { path = "../drivers/knvme" }
kvirtio = { path = "../drivers/kvirtio" }
kgoldfish-rtc = { path = "../drivers/kgoldfish-rtc" }
kcvitek-sd = { path = "../drivers/kcvitek-sd" }
k210-sdcard = { path = "../drivers/k210-sdcard" }
general-plic = { path = "../drivers/general-plic" }