[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
k210 = []
net = []

[dependencies]
frame_allocator = { path = "../modules/frame_allocator" }
logging = { path = "../modules/logging" }
panic_handler = { path = "../modules/panic_handler" }
kalloc = { path = "../modules/kalloc" }
log = "0.4"
devices = { path = "../modules/devices" }
hal = { path = "../modules/hal" }
arch = { path = "../arch" }
fs = { path = "../modules/fs" }
executor = { path = "../modules/executor" }
xmas-elf = "0.9.0"
sync = { path = "../modules/sync" }
bitflags = "2.0.2"
signal = { path = "../modules/signal" }
num_enum = { version = "0.6.1", default-features = false }
bit_field = "0.10.1"
kmacros = { path = "../modules/kmacros" }
lose-net-stack = { git = "https://github.com/yfblock/lose-net-stack", rev = "de965fe", features = ["log"]}
# lose-net-stack = { path = "../../lose-net-stack", features = ["log"]}
vfscore = { path = "../crates/vfscore" }
async-recursion = "1.0.4"
futures-lite = { version = "1.13.0", default-features = false, features=["alloc"] }