[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frame_allocator = { path = "../modules/frame_allocator" }
logging = { path = "../modules/logging" }
panic_handler = { path = "../modules/panic_handler" }
kalloc = { path = "../modules/kalloc" }
log = "0.4.17"
devices = { path = "../modules/devices" }
hal = { path = "../modules/hal" }
arch = { path = "../arch" }
