# 编译的目标平台
[build]
target = 'riscv64imac-unknown-none-elf'
# target = 'x86_64-unknown-none'

# This flags also can be set from every target.
rustflags = [
    '-Cforce-frame-pointers=yes',
    '-Clink-arg=-Tconfig/linker-general.ld',
    '--cfg=board="qemu"',
    '--cfg=driver="kvirtio,kgoldfish-rtc,general-plic,ns16550a"',
    '-Zunstable-options',
    '--check-cfg=values(board, "qemu","k210","cv1811h", "")'
]

[target.riscv64imac-unknown-none-elf]

[target.x86_64-unknown-none]

[unstable]
features = ['dev_dep','host_dep']
