[package]
name = "executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-queue = { version = "0.3.8", default-features = false, features = ["alloc"] }
arch = { git = "https://github.com/Byte-OS/arch.git" }
sync = { git = "https://github.com/Byte-OS/sync.git" }
log = "0.4"
downcast-rs = { version = "1.2.0", default-features = false }
