[package]
name = "kmacros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linkme = { version = "0.3.9", features = ["used_linker"] }
